### ISSUE TITLE
Models checkpoints

### ISSUE THREAD

**Issue by SilverSolver** [OSU-NLP-Group/GrokkedTransformer#1]
Hello! Thank you for your paper and your repo.
Is it possible to upload not only code, but also checkpoints of your models for various steps of training (i.e. before / after "grokking" happened)? It would be very helpful for researchers who want to continue to analyze how the inner representations or weights change after grokking or in different scenarios of training.
Thank you.

**Comment by Boshi-Wang** [comment]
The "downsampled" model checkpoints are now available; see the updated readme!

**Comment by SilverSolver** [comment]
Thank you!
