### ISSUE TITLE
No spec for Grokking model

### ISSUE THREAD

**Issue by Economax** [OSU-NLP-Group/GrokkedTransformer#3]
Hi,

From what I can tell, there is no way to replicate this paper quickly.

We would need for the Grokking model (Appendix F model) either:

1) Model spec 
2) Model weights

Preferably both.

Is this going to be added at some point?

**Comment by Boshi-Wang** [comment]
The "downsampled" model checkpoints are now available; see the updated readme!

**Comment by Economax** [comment]
Great!

However, I still have an issue:

In the paper, you write that memory is shared between the first 4 layers and the last 4 layers.

I don't find that implemented in the code anywhere.

I see code for the standard Universal Transformer and for sharing memory between every two layers. Not every four.

Did I miss something?

At any rate, a model spec for replicating your results with the complex reasoning section would be very nice - not just model weights!

**Comment by Boshi-Wang** [comment]
The parameter-sharing scheme is done implicitly; in `transformers/src/transformers/models/gpt2/modeling_gpt2.py` there's the option "add_recurrence" for the model forward pass, which runs the non-embedding layers for the second round. So if you want to run the setting in our paper, you just need to run the main scripts with 4 layers and the --add_recurrence flag.

We are not using the parameter-sharing scheme for the complex reasoning section (not sure if you misunderstood this earlier but just in case), and used the normal transformer & setting. So to reproduce the results, you can set

$1=cplx_reasoning
$2=0.1
$3=8
$4=your GPU

and run the main script. You can also check the config files accompanying the model weights. Hope this helps!
